// Mock data for Escrow Holds
export const ESCROW_STAGES = [
    { key: 1, label: 'Offer Sent', color: '#6366F1' },
    { key: 2, label: 'Offer Accepted', color: '#8B5CF6' },
    { key: 3, label: 'Pre-Arrival', color: '#F59E0B' },
    { key: 4, label: 'Arrived - Code Generated', color: '#3B82F6' },
    { key: 5, label: 'Code Exchanged', color: '#10B981' },
    { key: 6, label: 'Clocked In', color: '#22C55E' },
    { key: 7, label: 'Clocked Out', color: '#14B8A6' },
    { key: 8, label: 'Pending Payout', color: '#F97316' },
    { key: 9, label: 'Paid Out', color: '#16A34A' },
];

export const DISPUTE_REASONS = [
    'No show / Did not attend',
    'Late arrival / Early departure',
    'Payment issue (incorrect hours, amount, etc.)',
    'Work quality issue',
    'Misconduct or unprofessional behavior',
    'Incomplete work / Tasks not finished',
    'Safety or compliance issue',
    'Disagreement on hours worked',
    'Disagreement on job duties',
    'Fraudulent or false information',
    'Communication issue',
    'Other (please specify)',
];

export const activeHoldsData = [
    {
        id: 'hold-1',
        jobTitle: 'Warehouse Associate - Night Shift',
        company: 'Amazon Fulfillment Center',
        location: '1234 Industrial Blvd, Los Angeles, CA',
        candidate: { name: 'John Doe', initials: 'JD', email: 'john.doe@email.com', phone: '(555) 123-4567', color: '#6366F1' },
        shiftDate: 'Today, Feb 8',
        shiftTime: '10:00 PM - 6:00 AM',
        breakTime: '2:00 AM - 2:30 AM',
        amountOnHold: 240.00,
        currentStage: 6,
        clockInCode: '4832',
        jobId: '#JOB-2024-0892',
        description: 'Loading and unloading packages, inventory management, operating forklifts.',
        notes: 'Worker must wear steel-toe boots and safety vest.',
        timeline: [
            { stage: 1, label: 'Offer Sent', date: 'Feb 7, 2024', time: '2:30 PM', description: 'Recruiter sent job offer to candidate' },
            { stage: 2, label: 'Offer Accepted', date: 'Feb 7, 2024', time: '3:15 PM', description: 'Jobseeker accepted; matchmaking fee deducted ($25.00)' },
            { stage: 3, label: 'Pre-Arrival', date: 'Feb 8, 2024', time: '9:30 PM', description: 'Jobseeker en route; live tracking activated' },
            { stage: 4, label: 'Arrived - Code Generated', date: 'Feb 8, 2024', time: '9:58 PM', description: 'Jobseeker marked arrived; verification codes generated' },
            { stage: 5, label: 'Code Exchanged', date: 'Feb 8, 2024', time: '10:05 PM', description: 'Both parties verified codes; clock-in unlocked' },
            { stage: 6, label: 'Clocked In', date: 'Feb 8, 2024', time: '10:00 PM', description: 'Shift started; worker officially clocked in' },
            { stage: 7, label: 'Clocked Out', date: null, time: null, description: 'Shift ends; worker clocks out' },
            { stage: 8, label: 'Pending Payout', date: null, time: null, description: '7-day hold period started; funds secured' },
            { stage: 9, label: 'Paid Out', date: null, time: null, description: 'Funds to be released to jobseeker' },
        ],
    },
    {
        id: 'hold-2',
        jobTitle: 'Delivery Driver',
        company: 'UPS',
        location: '567 Ocean Ave, Santa Monica, CA',
        candidate: { name: 'Sarah Johnson', initials: 'SJ', email: 'sarah.j@email.com', phone: '(555) 987-6543', color: '#EC4899' },
        shiftDate: 'Tomorrow, Feb 9',
        shiftTime: '8:00 AM - 4:00 PM',
        breakTime: '12:00 PM - 12:30 PM',
        amountOnHold: 0,
        currentStage: 3,
        clockInCode: null,
        jobId: '#JOB-2024-0901',
        description: 'Package delivery routes in Santa Monica area.',
        notes: 'Must have valid driver license. Vehicle provided.',
        timeline: [
            { stage: 1, label: 'Offer Sent', date: 'Feb 8, 2024', time: '11:00 AM', description: 'Recruiter sent job offer to candidate' },
            { stage: 2, label: 'Offer Accepted', date: 'Feb 8, 2024', time: '11:30 AM', description: 'Jobseeker accepted; matchmaking fee deducted ($25.00)' },
            { stage: 3, label: 'Pre-Arrival', date: 'Feb 9, 2024', time: '7:45 AM', description: 'Jobseeker en route; live tracking activated' },
            { stage: 4, label: 'Arrived - Code Generated', date: null, time: null, description: 'Awaiting arrival' },
            { stage: 5, label: 'Code Exchanged', date: null, time: null, description: 'Awaiting code exchange' },
            { stage: 6, label: 'Clocked In', date: null, time: null, description: 'Awaiting clock in' },
            { stage: 7, label: 'Clocked Out', date: null, time: null, description: 'Awaiting clock out' },
            { stage: 8, label: 'Pending Payout', date: null, time: null, description: 'Awaiting hold period' },
            { stage: 9, label: 'Paid Out', date: null, time: null, description: 'Awaiting payout' },
        ],
    },
    {
        id: 'hold-3',
        jobTitle: 'Construction Helper',
        company: 'BuildCorp',
        location: '890 Main St, Pasadena, CA',
        candidate: { name: 'Mike Rodriguez', initials: 'MR', email: 'mike.r@email.com', phone: '(555) 456-7890', color: '#DC2626' },
        shiftDate: 'Feb 6, 2024',
        shiftTime: '7:00 AM - 3:00 PM',
        breakTime: '11:30 AM - 12:00 PM',
        amountOnHold: 240.00,
        currentStage: 8,
        clockInCode: '7291',
        payoutDaysRemaining: 5,
        jobId: '#JOB-2024-0878',
        description: 'General construction assistance - material handling, site cleanup.',
        notes: 'Hard hat and safety boots required.',
        timeline: [
            { stage: 1, label: 'Offer Sent', date: 'Feb 5, 2024', time: '9:00 AM', description: 'Recruiter sent job offer to candidate' },
            { stage: 2, label: 'Offer Accepted', date: 'Feb 5, 2024', time: '9:30 AM', description: 'Jobseeker accepted; matchmaking fee deducted ($25.00)' },
            { stage: 3, label: 'Pre-Arrival', date: 'Feb 6, 2024', time: '6:45 AM', description: 'Jobseeker en route; live tracking activated' },
            { stage: 4, label: 'Arrived - Code Generated', date: 'Feb 6, 2024', time: '6:55 AM', description: 'Jobseeker marked arrived; verification codes generated' },
            { stage: 5, label: 'Code Exchanged', date: 'Feb 6, 2024', time: '6:58 AM', description: 'Both parties verified codes; clock-in unlocked' },
            { stage: 6, label: 'Clocked In', date: 'Feb 6, 2024', time: '7:00 AM', description: 'Shift started; worker officially clocked in' },
            { stage: 7, label: 'Clocked Out', date: 'Feb 6, 2024', time: '3:00 PM', description: 'Shift completed; worker clocked out' },
            { stage: 8, label: 'Pending Payout', date: 'Feb 6, 2024', time: '3:05 PM', description: '7-day hold period started; funds secured' },
            { stage: 9, label: 'Paid Out', date: 'Estimated: Feb 13', time: null, description: 'Funds to be released to jobseeker' },
        ],
    },
];

export const completedHoldsData = [
    {
        id: 'hold-c1',
        jobTitle: 'Commercial Painting',
        company: 'BuildRight Pty Ltd',
        location: 'Downtown Office, Room 301',
        candidate: { name: 'Robert Johnson', initials: 'RJ', email: 'robert.j@email.com', phone: '(555) 321-0987', color: '#16A34A' },
        shiftDate: 'Jan 28, 2024',
        shiftTime: '9:00 AM - 5:00 PM',
        breakTime: '12:00 PM - 12:30 PM',
        amountOnHold: 200.00,
        currentStage: 9,
        status: 'Paid Out',
        clockInCode: '6412',
        jobId: '#JOB-2024-0801',
        description: 'Commercial interior painting — 2 offices + hallway.',
        notes: 'Paint and supplies provided on site.',
        timeline: [
            { stage: 1, label: 'Offer Sent', date: 'Jan 27, 2024', time: '10:00 AM', description: 'Recruiter sent job offer to candidate' },
            { stage: 2, label: 'Offer Accepted', date: 'Jan 27, 2024', time: '10:45 AM', description: 'Jobseeker accepted; matchmaking fee deducted ($25.00)' },
            { stage: 3, label: 'Pre-Arrival', date: 'Jan 28, 2024', time: '8:30 AM', description: 'Jobseeker en route' },
            { stage: 4, label: 'Arrived - Code Generated', date: 'Jan 28, 2024', time: '8:50 AM', description: 'Verification codes generated' },
            { stage: 5, label: 'Code Exchanged', date: 'Jan 28, 2024', time: '8:55 AM', description: 'Codes verified; clock-in unlocked' },
            { stage: 6, label: 'Clocked In', date: 'Jan 28, 2024', time: '9:00 AM', description: 'Shift started' },
            { stage: 7, label: 'Clocked Out', date: 'Jan 28, 2024', time: '5:00 PM', description: 'Shift completed' },
            { stage: 8, label: 'Pending Payout', date: 'Jan 28, 2024', time: '5:05 PM', description: '7-day hold period started' },
            { stage: 9, label: 'Paid Out', date: 'Feb 4, 2024', time: '6:00 AM', description: 'Funds released to jobseeker' },
        ],
    },
    {
        id: 'hold-c2',
        jobTitle: 'Event Staff',
        company: 'EventPro Services',
        location: '456 Convention Center Dr',
        candidate: { name: 'Lisa Chen', initials: 'LC', email: 'lisa.c@email.com', phone: '(555) 654-3210', color: '#8B5CF6' },
        shiftDate: 'Jan 20, 2024',
        shiftTime: '6:00 PM - 11:00 PM',
        breakTime: '8:30 PM - 8:45 PM',
        amountOnHold: 150.00,
        currentStage: 9,
        status: 'Refunded',
        clockInCode: '2198',
        jobId: '#JOB-2024-0756',
        description: 'Event setup and guest coordination.',
        notes: 'Black attire required.',
        timeline: [
            { stage: 1, label: 'Offer Sent', date: 'Jan 19, 2024', time: '3:00 PM', description: 'Recruiter sent job offer' },
            { stage: 2, label: 'Offer Accepted', date: 'Jan 19, 2024', time: '3:30 PM', description: 'Jobseeker accepted; fee deducted ($25.00)' },
            { stage: 3, label: 'Pre-Arrival', date: 'Jan 20, 2024', time: '5:30 PM', description: 'Jobseeker en route' },
            { stage: 4, label: 'Arrived - Code Generated', date: 'Jan 20, 2024', time: '5:50 PM', description: 'Codes generated' },
            { stage: 5, label: 'Code Exchanged', date: 'Jan 20, 2024', time: '5:55 PM', description: 'Codes verified' },
            { stage: 6, label: 'Clocked In', date: 'Jan 20, 2024', time: '6:00 PM', description: 'Shift started' },
            { stage: 7, label: 'Clocked Out', date: 'Jan 20, 2024', time: '11:00 PM', description: 'Shift completed' },
            { stage: 8, label: 'Pending Payout', date: 'Jan 20, 2024', time: '11:05 PM', description: '7-day hold' },
            { stage: 9, label: 'Refunded', date: 'Jan 25, 2024', time: '2:00 PM', description: 'Dispute resolved — partial refund issued ($50.00)' },
        ],
    },
];
