// Mock transaction data for wallet

export const TRANSACTION_CATEGORIES = [
    'All Transactions',
    'Coins Purchased',
    'Matchmaking Fees Paid',
    'Salary Holds',
    'Withdrawals',
    'Refunds',
    'Referrals Bonus',
];

export const DATE_FILTERS = ['Daily', 'Weekly', 'Fortnightly', 'Monthly'];

export const STATUS_FILTERS = ['All', 'Completed', 'Pending', 'Cancelled'];

export const TRANSACTION_SUMMARY = [
    { key: 'coins_purchased', label: 'Coins Purchased', value: 1250.00, icon: 'wallet-outline', color: '#6366F1' },
    { key: 'matchmaking_fees', label: 'Matchmaking Fees Paid', value: 375.00, icon: 'people-outline', color: '#EC4899' },
    { key: 'salary_holds', label: 'Salary Holds', value: 720.00, icon: 'shield-checkmark-outline', color: '#F97316' },
    { key: 'withdrawals', label: 'Withdrawals', value: 500.00, icon: 'arrow-up-circle-outline', color: '#8B5CF6' },
    { key: 'refunds', label: 'Refunds', value: 75.00, icon: 'arrow-undo-outline', color: '#14B8A6' },
    { key: 'referrals_bonus', label: 'Referrals Bonus', value: 50.00, icon: 'gift-outline', color: '#16A34A' },
];

export const transactionHistory = [
    {
        id: 'tx-1',
        txnId: 'TXN-240208-00',
        date: 'Feb 8, 2024',
        name: 'Matchmaking Fee - Job #892',
        category: 'Matchmaking Fees Paid',
        categoryShort: 'Fees',
        description: 'Job matching service',
        jobCandidate: 'Job #892 - John Doe',
        type: 'Debit',
        amount: 25.00,
        status: 'Completed',
    },
    {
        id: 'tx-2',
        txnId: 'TXN-240207-00',
        date: 'Feb 7, 2024',
        name: 'Coins Purchase (500 coins)',
        category: 'Coins Purchased',
        categoryShort: 'Coins',
        description: '500 coins purchased',
        jobCandidate: 'N/A',
        type: 'Debit',
        amount: 50.00,
        status: 'Completed',
    },
    {
        id: 'tx-3',
        txnId: 'TXN-240205-00',
        date: 'Feb 5, 2024',
        name: 'Salary Hold - Warehouse Associate',
        category: 'Salary Holds',
        categoryShort: 'Hold',
        description: 'Warehouse night shift',
        jobCandidate: 'Job #890 - Sarah J.',
        type: 'Credit',
        amount: 240.00,
        status: 'Pending',
    },
    {
        id: 'tx-4',
        txnId: 'TXN-240203-00',
        date: 'Feb 3, 2024',
        name: 'Withdrawal to Bank ****4521',
        category: 'Withdrawals',
        categoryShort: 'Bank',
        description: 'Withdrawal to CBA ****4521',
        jobCandidate: 'N/A',
        type: 'Debit',
        amount: 500.00,
        status: 'Completed',
    },
    {
        id: 'tx-5',
        txnId: 'TXN-240201-00',
        date: 'Feb 1, 2024',
        name: 'Referral Bonus - User #1234',
        category: 'Referrals Bonus',
        categoryShort: 'Bonus',
        description: 'User #1234 referral',
        jobCandidate: 'New User: Mike R.',
        type: 'Credit',
        amount: 25.00,
        status: 'Completed',
    },
    {
        id: 'tx-6',
        txnId: 'TXN-240128-00',
        date: 'Jan 28, 2024',
        name: 'Matchmaking Fee - Job #889',
        category: 'Matchmaking Fees Paid',
        categoryShort: 'Fees',
        description: 'Job matching service',
        jobCandidate: 'Job #889 - Lisa C.',
        type: 'Debit',
        amount: 25.00,
        status: 'Completed',
    },
    {
        id: 'tx-7',
        txnId: 'TXN-240125-00',
        date: 'Jan 25, 2024',
        name: 'Refund - Job #885 Cancelled',
        category: 'Refunds',
        categoryShort: 'Refund',
        description: 'Job #885 cancellation refund',
        jobCandidate: 'Job #885 - David P.',
        type: 'Credit',
        amount: 75.00,
        status: 'Completed',
    },
    {
        id: 'tx-8',
        txnId: 'TXN-240122-00',
        date: 'Jan 22, 2024',
        name: 'Salary Payout - Driver Job',
        category: 'Salary Holds',
        categoryShort: 'Hold',
        description: 'Driver shift salary payout',
        jobCandidate: 'Job #880 - Tom W.',
        type: 'Credit',
        amount: 180.00,
        status: 'Completed',
    },
    {
        id: 'tx-9',
        txnId: 'TXN-240120-00',
        date: 'Jan 20, 2024',
        name: 'Coins Purchase (200 coins)',
        category: 'Coins Purchased',
        categoryShort: 'Coins',
        description: '200 coins purchased',
        jobCandidate: 'N/A',
        type: 'Debit',
        amount: 20.00,
        status: 'Cancelled',
    },
    {
        id: 'tx-10',
        txnId: 'TXN-240118-00',
        date: 'Jan 18, 2024',
        name: 'Matchmaking Fee - Job #882',
        category: 'Matchmaking Fees Paid',
        categoryShort: 'Fees',
        description: 'Job matching service',
        jobCandidate: 'Job #882 - Amy L.',
        type: 'Debit',
        amount: 25.00,
        status: 'Completed',
    },
    {
        id: 'tx-11',
        txnId: 'TXN-240115-00',
        date: 'Jan 15, 2024',
        name: 'Coins Purchase (1000 coins)',
        category: 'Coins Purchased',
        categoryShort: 'Coins',
        description: '1000 coins purchased',
        jobCandidate: 'N/A',
        type: 'Debit',
        amount: 100.00,
        status: 'Completed',
    },
    {
        id: 'tx-12',
        txnId: 'TXN-240112-00',
        date: 'Jan 12, 2024',
        name: 'Salary Hold - Retail Assistant',
        category: 'Salary Holds',
        categoryShort: 'Hold',
        description: 'Retail shift salary hold',
        jobCandidate: 'Job #875 - David P.',
        type: 'Credit',
        amount: 180.00,
        status: 'Completed',
    },
    {
        id: 'tx-13',
        txnId: 'TXN-240110-00',
        date: 'Jan 10, 2024',
        name: 'Matchmaking Fee - Job #878',
        category: 'Matchmaking Fees Paid',
        categoryShort: 'Fees',
        description: 'Job matching service',
        jobCandidate: 'Job #878 - Nick S.',
        type: 'Debit',
        amount: 25.00,
        status: 'Completed',
    },
    {
        id: 'tx-14',
        txnId: 'TXN-240108-00',
        date: 'Jan 8, 2024',
        name: 'Referral Bonus - User #1190',
        category: 'Referrals Bonus',
        categoryShort: 'Bonus',
        description: 'User #1190 referral',
        jobCandidate: 'New User: Emma K.',
        type: 'Credit',
        amount: 25.00,
        status: 'Completed',
    },
    {
        id: 'tx-15',
        txnId: 'TXN-240105-00',
        date: 'Jan 5, 2024',
        name: 'Withdrawal to Bank ****4521',
        category: 'Withdrawals',
        categoryShort: 'Bank',
        description: 'Withdrawal to CBA ****4521',
        jobCandidate: 'N/A',
        type: 'Debit',
        amount: 300.00,
        status: 'Completed',
    },
    {
        id: 'tx-16',
        txnId: 'TXN-240103-00',
        date: 'Jan 3, 2024',
        name: 'Coins Purchase (300 coins)',
        category: 'Coins Purchased',
        categoryShort: 'Coins',
        description: '300 coins purchased',
        jobCandidate: 'N/A',
        type: 'Debit',
        amount: 30.00,
        status: 'Completed',
    },
    {
        id: 'tx-17',
        txnId: 'TXN-231230-00',
        date: 'Dec 30, 2023',
        name: 'Salary Hold - Event Staff',
        category: 'Salary Holds',
        categoryShort: 'Hold',
        description: 'Event staff salary hold',
        jobCandidate: 'Job #870 - Lisa C.',
        type: 'Credit',
        amount: 150.00,
        status: 'Completed',
    },
    {
        id: 'tx-18',
        txnId: 'TXN-231228-00',
        date: 'Dec 28, 2023',
        name: 'Matchmaking Fee - Job #870',
        category: 'Matchmaking Fees Paid',
        categoryShort: 'Fees',
        description: 'Job matching service',
        jobCandidate: 'Job #870 - Lisa C.',
        type: 'Debit',
        amount: 25.00,
        status: 'Completed',
    },
    {
        id: 'tx-19',
        txnId: 'TXN-231225-00',
        date: 'Dec 25, 2023',
        name: 'Coins Purchase (500 coins)',
        category: 'Coins Purchased',
        categoryShort: 'Coins',
        description: '500 coins purchased',
        jobCandidate: 'N/A',
        type: 'Debit',
        amount: 50.00,
        status: 'Completed',
    },
    {
        id: 'tx-20',
        txnId: 'TXN-231222-00',
        date: 'Dec 22, 2023',
        name: 'Salary Payout - Painting Job',
        category: 'Salary Holds',
        categoryShort: 'Hold',
        description: 'Commercial painting payout',
        jobCandidate: 'Job #865 - Robert J.',
        type: 'Credit',
        amount: 200.00,
        status: 'Completed',
    },
    {
        id: 'tx-21',
        txnId: 'TXN-231220-00',
        date: 'Dec 20, 2023',
        name: 'Withdrawal to Bank ****4521',
        category: 'Withdrawals',
        categoryShort: 'Bank',
        description: 'Withdrawal to CBA ****4521',
        jobCandidate: 'N/A',
        type: 'Debit',
        amount: 200.00,
        status: 'Completed',
    },
    {
        id: 'tx-22',
        txnId: 'TXN-231218-00',
        date: 'Dec 18, 2023',
        name: 'Matchmaking Fee - Job #865',
        category: 'Matchmaking Fees Paid',
        categoryShort: 'Fees',
        description: 'Job matching service',
        jobCandidate: 'Job #865 - Robert J.',
        type: 'Debit',
        amount: 25.00,
        status: 'Completed',
    },
    {
        id: 'tx-23',
        txnId: 'TXN-231215-00',
        date: 'Dec 15, 2023',
        name: 'Coins Purchase (1000 coins)',
        category: 'Coins Purchased',
        categoryShort: 'Coins',
        description: '1000 coins purchased',
        jobCandidate: 'N/A',
        type: 'Debit',
        amount: 100.00,
        status: 'Completed',
    },
    {
        id: 'tx-24',
        txnId: 'TXN-231210-00',
        date: 'Dec 10, 2023',
        name: 'Salary Hold - Construction Helper',
        category: 'Salary Holds',
        categoryShort: 'Hold',
        description: 'Construction helper salary hold',
        jobCandidate: 'Job #860 - Mike R.',
        type: 'Credit',
        amount: 240.00,
        status: 'Completed',
    },
];
