export const EXTRA_QUALIFICATIONS_OPTIONS = [
  { key: 'white_card', title: 'White Card (Construction)' },
  { key: 'police_check', title: 'Police Check' },
  { key: 'wwcc', title: 'Working With Children Check (WWCC)' },
  { key: 'ndis', title: 'NDIS Worker Screening Check' },
  { key: 'first_aid', title: 'First Aid Certificate' },
  { key: 'cpr', title: 'CPR Certificate' },
  { key: 'rsa', title: 'RSA (Responsible Service of Alcohol)' },
  { key: 'rcg', title: 'RCG (Responsible Conduct of Gambling)' },
  { key: 'food_handling', title: 'Food Handling Certificate' },
  { key: 'covid_vax', title: 'COVID-19 Vaccination Certificate' },
  { key: 'manual_handling', title: 'Manual Handling Certificate' },
  { key: 'driver_full', title: 'Driver Licence (Full)' },
  { key: 'driver_provisional', title: 'Provisional Licence (P1/P2)' },
  {
    key: 'hr_mr_lr_hc_mc',
    title: 'HR/MR/LR/HC/MC Licence (specify)',
    requiresText: true,
    textPlaceholder: 'Specify HR/MR/LR/HC/MC',
  },
  { key: 'forklift', title: 'Forklift Licence' },
  { key: 'bus_authority', title: 'Bus Driver Authority' },
  { key: 'taxi_accreditation', title: 'Taxi Driver Accreditation' },
  { key: 'dangerous_goods', title: 'Dangerous Goods Licence' },
  {
    key: 'high_risk',
    title: 'High Risk Work Licence (specify)',
    requiresText: true,
    textPlaceholder: 'Please specify',
  },
  { key: 'ewp', title: 'EWP Ticket' },
  { key: 'traffic_control', title: 'Traffic Control Ticket' },
  { key: 'asbestos', title: 'Asbestos Removal Licence' },
  { key: 'confined_space', title: 'Confined Space Entry Ticket' },
  { key: 'working_heights', title: 'Working at Heights Ticket' },
  { key: 'electrical', title: 'Electrical Licence' },
  { key: 'plumbing', title: 'Plumbing Licence' },
  { key: 'gas_fitter', title: 'Gas Fitter Licence' },
  { key: 'wwvp', title: 'WWVP Card' },
  { key: 'ahpra', title: 'AHPRA Registration' },
  { key: 'med_admin', title: 'Medication Administration Certificate' },
  { key: 'mental_health_first_aid', title: 'Mental Health First Aid' },
  { key: 'disability_support', title: 'Disability Support Worker Certificate' },
  { key: 'barista', title: 'Barista Certificate' },
  { key: 'food_safety', title: 'Food Safety Supervisor Certificate' },
  { key: 'gaming_licence', title: 'Gaming Licence' },
  { key: 'order_picker', title: 'Order Picker Licence' },
  { key: 'warehouse_induction', title: 'Warehouse Induction Card' },
  { key: 'security_licence', title: 'Security Licence' },
  { key: 'msic_asic', title: 'MSIC/ASIC Card' },
  { key: 'boat_licence', title: 'Boat Licence' },
  { key: 'firearms_licence', title: 'Firearms Licence' },
  { key: 'q_fever', title: 'Q Fever Vaccination Card' },
  { key: 'animals_permit', title: 'Working With Animals Permit' },
  { key: 'other', title: 'Other (please specify)', requiresText: true, textPlaceholder: 'Please specify' },
]

export const PREFERRED_LANGUAGES_OPTIONS = [
  { key: 'english', title: 'English' },
  { key: 'mandarin', title: 'Mandarin (Chinese)' },
  { key: 'cantonese', title: 'Cantonese' },
  { key: 'hindi', title: 'Hindi' },
  { key: 'punjabi', title: 'Punjabi' },
  { key: 'arabic', title: 'Arabic' },
  { key: 'vietnamese', title: 'Vietnamese' },
  { key: 'tagalog', title: 'Tagalog (Filipino)' },
  { key: 'spanish', title: 'Spanish' },
  { key: 'italian', title: 'Italian' },
  { key: 'greek', title: 'Greek' },
  { key: 'korean', title: 'Korean' },
  { key: 'japanese', title: 'Japanese' },
  { key: 'thai', title: 'Thai' },
  { key: 'tamil', title: 'Tamil' },
  { key: 'urdu', title: 'Urdu' },
  { key: 'nepali', title: 'Nepali' },
  { key: 'turkish', title: 'Turkish' },
  { key: 'indonesian', title: 'Indonesian' },
  { key: 'samoan', title: 'Samoan' },
  { key: 'fijian', title: 'Fijian' },
  { key: 'german', title: 'German' },
  { key: 'french', title: 'French' },
  { key: 'portuguese', title: 'Portuguese' },
  { key: 'russian', title: 'Russian' },
  { key: 'serbian', title: 'Serbian' },
  { key: 'croatian', title: 'Croatian' },
  { key: 'sinhalese', title: 'Sinhalese' },
  { key: 'bengali', title: 'Bengali' },
  { key: 'dari', title: 'Dari' },
  { key: 'pashto', title: 'Pashto' },
  { key: 'malay', title: 'Malay' },
  { key: 'burmese', title: 'Burmese' },
  { key: 'khmer', title: 'Khmer (Cambodian)' },
  { key: 'polish', title: 'Polish' },
  { key: 'macedonian', title: 'Macedonian' },
  { key: 'afrikaans', title: 'Afrikaans' },
  { key: 'other', title: 'Other (please specify)', requiresText: true, textPlaceholder: 'Please specify' },
]

