/**
 * Centralized Application Data
 * Contains all static data for titles, job categories, countries, languages, and visa types
 */

// User Titles
export const USER_TITLES = [
  { id: 1, title: 'DR' },
  { id: 2, title: 'MR' },
  { id: 3, title: 'MS' },
  { id: 4, title: 'MRS' },
  { id: 5, title: 'MISS' },
  { id: 6, title: 'Other' },
];

// Job Categories with Sub Categories
export const JOB_CATEGORIES = {
  'Hospitality & Tourism': [
    'Chef & Cook',
    'Kitchen & Sandwich Hand',
    'Bar & Beverage Staff',
    'Waiting Staff',
    'Front Office & Guest Services',
    'Management',
    'Tour Guide',
    'Travel Agent/Consultant',
  ],
  'Trades & Services': [
    'Labourer',
    'Cleaner & Housekeeper',
    'Building Trades',
    'Automotive Trades',
    'Hair & Beauty Services',
    'Gardening & Landscaping',
    'Carpentry & Cabinet Making',
    'Printer & Sign Writer',
    'Plumber',
    'Technician',
    'Electrician',
    'Maintenance & Handyman',
    'Welder & Boilermaker',
    'Removalist',
    'Security Services',
    'Air Conditioning & Refrigeration',
    'Bakers & Pastry Chefs',
    'Fitter/Turner & Machinist',
    'Butcher',
    'Nanny & Babysitter',
    'Printing & Publishing Services',
    'Florist',
    'Locksmith',
    'Tailor & Dressmaker',
  ],
  'Manufacturing, Transport & Logistics': [
    'Courier/Driver & Postal Service',
    'Road Transport',
    'Warehousing/Storage & Distribution',
    'Assembly & Process Work',
    'Machine Operator',
    'Freight/Cargo Forwarding',
    'Production/Planning & Scheduling',
  ],
  'Construction': [
    'Machine & Plant Operator',
    'Foreman/Supervisor',
    'Contract Management',
    'Project Management',
  ],
  'Farming & Veterinary': [
    'Agronomy & Farm Services',
    'Horticulture',
    'Farm Management',
    'Vet & Animal Welfare',
  ],
  'Retail': [
    'Retail Assistant',
    'Retail Management',
    'Merchandiser',
  ],
  'Education & Teaching': [
    'Tutoring',
    'Childcare & After School Care',
    'Teaching',
    'Workplace Training & Assessment',
  ],
  'Community Services & Development': [
    'Aged & Disability Support',
    'Child Welfare, Youth & Family Services',
  ],
  'Healthcare & Nursing': [
    'Nursing',
    'Dental & Dentist',
    'Pharmacy',
    'Physiotherapy, OT & Rehabilitation',
    'Healthcare Administration',
    'General Practitioner',
  ],
  'Sales': [
    'Sales Representative/ Consultant',
    'New Business Development',
    'Sales Management',
    'Relationship & Account Management',
    'Sales Coordinator',
  ],
  'Administration & Office Support': [
    'Administrative Assistant',
    'Receptionist',
    'PA, EA & Secretary',
  ],
  'Accounting': [
    'Bookkeeping & Small Practice Accounting',
    'Taxation',
    'Accounts Officer/ Clerk',
    'Financial Accounting & Reporting',
    'Payroll Accounting',
    'Accounts Receivable/ Credit Control',
    'Accounts Payable',
    'Business Services & Corporate Advisory',
    'Financial Manager & Controller',
  ],
  'Information & Communication Technology': [
    'IT Support & Help Desk',
    'Developer/ Programmer',
    'Web Development & Production',
    'Systems/ Business Analyst',
  ],
  'Call Centre & Customer Service': [
    'Customer Service- Customer Facing',
    'Sales- Call Centre',
    'Customer Service- Call Centre',
    'Sales- Customer Facing',
  ],
  'Design & Architecture': [
    'Architecture',
    'Graphic Design',
    'Interior Design',
    'Interaction & Web Design',
  ],
  'Advertising, Arts & Media': [
    'Performing Arts',
    'Writing & Journalist',
    'Media Planning, Strategy & Buying',
  ],
  'Marketing & Communication': [
    'Marketing Communications',
    'Digital & Search Marketing',
    'Marketing Assistants',
    'Marketing Manager',
    'Trade Marketing',
  ],
  'Engineering': [
    'Automatic Engineering',
    'Civil/ Structural Engineering',
    'Maintenance',
    'Mechanical Engineering',
    'Building Services Engineering',
  ],
  'Sports & Recreation': [
    'Coaching & Instruction',
    'Personal Trainer',
  ],
  'Real Estate & Property': [
    'Residential Leasing & Property Management',
    'Residential Sales',
    'Admin',
    'Commercial Sales, Leasing & Property Management',
    'Facilities Management & Body Corporate',
  ],
  'Mining, Resources & Energy': [
    'Mining- Operations',
    'Mining- Engineering & Maintenance',
    'Oil & Gas- Operations',
  ],
  'Recruitment & HR': [
    'Consulting & Generalist HR',
    'Recruitment - Internal',
    'Recruitment- Agency',
  ],
  'Legal': [
    'Generalist',
    'Corporate & Commercial Law',
    'Legal Secretary',
    'Property Law',
  ],
  'Banking & Financial Services': [
    'Account & Relationship Management',
    'Banking – Retail/ Branch',
    'Funds Management',
  ],
  'Government & Defence': [
    'Government',
  ],
  'Others': [],
};

// Countries List (Alphabetical)
export const COUNTRIES = [
  'Afghanistan',
  'Äland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua & Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Ascension Island',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia & Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Canary Islands',
  'Cape Verde',
  'Caribbean Netherlands',
  'Cayman Islands',
  'Central African Repubic',
  'Ceuta & Melilla',
  'Chad',
  'Chagos Archipelago',
  'Chile',
  'China mainland',
  'Christmas Island',
  'Clipperton Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo - Brazzaville',
  'Congo – Kinshasa',
  'Cook Islands',
  'Costa Rica',
  'Côte d\'Ivoire',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Diego Garcia',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard & McDonald Islands',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'KosoVo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar (Burma)',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Macedonia',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestinian Territories',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn Islands',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Réunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Samoa',
  'San Marino',
  'São Tomé & Príncipe',
  'Sark',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'So. Georgia & So. Sandwich Isl.',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'St Helena',
  'St Pierre & Miquelon',
  'St. Barthélemy',
  'St. Kitts & Nevis',
  'St. Lucia',
  'St. Martin',
  'St. Vincent & Grenadines',
  'Suriname',
  'Svalbard & Jan Mayen',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad & Tobago',
  'Tristan da Cunha',
  'Tunisia',
  'Türkiye',
  'Turkmenistan',
  'Turks & Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'US Outlying Islands',
  'US Virgin Islands',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Wallis & Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

// Languages List (same as countries)
export const LANGUAGES = [...COUNTRIES];

// Visa Types
export const VISA_TYPES = [
  { id: 1, title: 'Visitor visas', requiresSubclass: true },
  { id: 2, title: 'Studying and training visas', requiresSubclass: true },
  { id: 3, title: 'Family and partner visas', requiresSubclass: true },
  { id: 4, title: 'Working and skilled visas', requiresSubclass: true },
  { id: 5, title: 'Repealed visas', requiresSubclass: true },
  { id: 6, title: 'Other Visa type', requiresSubclass: false },
];

