const badgeLevels = ['Bronze', 'Silver', 'Gold', 'Platinum'];

export const DUMMY_JOB_SEEKERS = [
  {
    id: 'js-001',
    name: 'Jane Jobseeker',
    avatar: null,
    badge: 'Gold',
    acceptanceRating: 92,
    experienceYears: 4,
    industries: ['Construction', 'Maintenance'],
    preferredRoles: ['Painter', 'Decorator'],
    location: 'Sydney',
    suburb: 'Parramatta',
    radiusKm: 25,
    taxTypes: ['ABN'],
    languages: ['English'],
    qualifications: ['Certificate III in Painting and Decorating'],
    education: 'TAFE NSW',
    availability: {
      summary: 'Mon - Fri, 8 AM - 5 PM',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    },
    payPreference: {
      min: 28,
      max: 38,
    },
    bio: 'Detail-oriented painter with experience across residential and commercial projects.',
    skills: ['Painting', 'Surface Prep', 'Team Leadership'],
  },
  {
    id: 'js-002',
    name: 'Michael Torres',
    avatar: null,
    badge: 'Platinum',
    acceptanceRating: 88,
    experienceYears: 6,
    industries: ['Logistics', 'Warehousing'],
    preferredRoles: ['Warehouse Manager', 'Inventory Lead'],
    location: 'Melbourne',
    suburb: 'Footscray',
    radiusKm: 30,
    taxTypes: ['TFN', 'ABN'],
    languages: ['English', 'Spanish'],
    qualifications: ['Diploma in Logistics Management'],
    education: 'Victoria University',
    availability: {
      summary: 'Mon - Sat, Day shifts',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    payPreference: {
      min: 32,
      max: 45,
    },
    bio: 'Warehouse professional focused on process optimisation and safety.',
    skills: ['Inventory Systems', 'Team Training', 'Forklift Operation'],
  },
  {
    id: 'js-003',
    name: 'Aisha Khan',
    avatar: null,
    badge: 'Bronze',
    acceptanceRating: 78,
    experienceYears: 2,
    industries: ['Events', 'Hospitality'],
    preferredRoles: ['Event Crew', 'Logistics Assistant'],
    location: 'Brisbane',
    suburb: 'Fortitude Valley',
    radiusKm: 20,
    taxTypes: ['ABN'],
    languages: ['English', 'Hindi'],
    qualifications: ['Certificate II in Hospitality'],
    education: 'TAFE Queensland',
    availability: {
      summary: 'Thu - Sun, Afternoon & Night',
      days: ['Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    payPreference: {
      min: 22,
      max: 32,
    },
    bio: 'Reliable event crew member experienced with rapid setup and packdown.',
    skills: ['Customer Service', 'Manual Handling', 'Scheduling'],
  },
  {
    id: 'js-004',
    name: 'Liam Chen',
    avatar: null,
    badge: 'Silver',
    acceptanceRating: 84,
    experienceYears: 5,
    industries: ['Cleaning Services', 'Facilities'],
    preferredRoles: ['Cleaning Supervisor', 'Deep Cleaning Specialist'],
    location: 'Perth',
    suburb: 'Scarborough',
    radiusKm: 35,
    taxTypes: ['TFN'],
    languages: ['English', 'Mandarin'],
    qualifications: ['Workplace Health & Safety (Level 2)'],
    education: 'North Metropolitan TAFE',
    availability: {
      summary: 'Mon - Fri, Evening & Night',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    },
    payPreference: {
      min: 26,
      max: 36,
    },
    bio: 'Cleaning supervisor experienced with large commercial kitchens and hospitality venues.',
    skills: ['Team Leadership', 'Chemical Handling', 'Quality Assurance'],
  },
  {
    id: 'js-005',
    name: 'Sofia Romero',
    avatar: null,
    badge: 'Gold',
    acceptanceRating: 95,
    experienceYears: 7,
    industries: ['Landscaping', 'Outdoor Projects'],
    preferredRoles: ['Landscape Designer', 'Project Lead'],
    location: 'Adelaide',
    suburb: 'Norwood',
    radiusKm: 40,
    taxTypes: ['ABN'],
    languages: ['English', 'Spanish'],
    qualifications: ['Bachelor of Landscape Architecture'],
    education: 'University of Adelaide',
    availability: {
      summary: 'Mon - Sat, Flexible',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    payPreference: {
      min: 35,
      max: 55,
    },
    bio: 'Landscape professional specialising in bespoke outdoor experiences.',
    skills: ['Design', 'Site Management', 'Client Liaison'],
  },
  {
    id: 'js-006',
    name: 'Noah Wilson',
    avatar: null,
    badge: 'Bronze',
    acceptanceRating: 70,
    experienceYears: 1,
    industries: ['Retail', 'Customer Service'],
    preferredRoles: ['Store Assistant', 'Visual Merchandiser'],
    location: 'Gold Coast',
    suburb: 'Southport',
    radiusKm: 15,
    taxTypes: ['TFN'],
    languages: ['English'],
    qualifications: ['Certificate III in Retail'],
    education: 'TAFE Queensland',
    availability: {
      summary: 'Wed - Sun, Morning shifts',
      days: ['Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    payPreference: {
      min: 20,
      max: 28,
    },
    bio: 'Retail professional with an eye for detail and merchandising layouts.',
    skills: ['POS Systems', 'Visual Merchandising', 'Stock Control'],
  },
  {
    id: 'js-007',
    name: 'Emma Thompson',
    avatar: null,
    badge: 'PRO',
    acceptanceRating: 96,
    experienceYears: 8,
    industries: ['Construction', 'Carpentry'],
    preferredRoles: ['Carpenter', 'Site Supervisor'],
    location: 'Sydney',
    suburb: 'Liverpool',
    radiusKm: 50,
    taxTypes: ['ABN'],
    languages: ['English'],
    qualifications: ['Certificate III in Carpentry', 'White Card'],
    education: 'TAFE NSW',
    availability: {
      summary: 'Mon - Fri, 7 AM - 4 PM',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    },
    payPreference: {
      min: 40,
      max: 60,
    },
    bio: 'Experienced carpenter with expertise in residential and commercial construction.',
    skills: ['Framing', 'Finish Carpentry', 'Blueprint Reading', 'Team Leadership'],
  },
  {
    id: 'js-008',
    name: 'James Anderson',
    avatar: null,
    badge: 'Silver',
    acceptanceRating: 82,
    experienceYears: 3,
    industries: ['Hospitality', 'Food Service'],
    preferredRoles: ['Chef', 'Kitchen Hand', 'Catering Assistant'],
    location: 'Melbourne',
    suburb: 'CBD',
    radiusKm: 20,
    taxTypes: ['TFN', 'ABN'],
    languages: ['English', 'French'],
    qualifications: ['Certificate III in Commercial Cookery'],
    education: 'William Angliss Institute',
    availability: {
      summary: 'Mon - Sun, Flexible',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    payPreference: {
      min: 25,
      max: 35,
    },
    bio: 'Passionate chef with experience in fine dining and event catering.',
    skills: ['Food Prep', 'Menu Planning', 'Kitchen Management'],
  },
  {
    id: 'js-009',
    name: 'Olivia Martinez',
    avatar: null,
    badge: 'Gold',
    acceptanceRating: 89,
    experienceYears: 5,
    industries: ['Administration', 'Office Support'],
    preferredRoles: ['Administrative Assistant', 'Office Manager'],
    location: 'Brisbane',
    suburb: 'Fortitude Valley',
    radiusKm: 25,
    taxTypes: ['TFN'],
    languages: ['English', 'Spanish'],
    qualifications: ['Diploma of Business Administration'],
    education: 'Brisbane TAFE',
    availability: {
      summary: 'Mon - Fri, 9 AM - 5 PM',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    },
    payPreference: {
      min: 28,
      max: 40,
    },
    bio: 'Organized administrative professional with strong communication skills.',
    skills: ['Microsoft Office', 'Data Entry', 'Customer Service', 'Scheduling'],
  },
  {
    id: 'js-010',
    name: 'David Kim',
    avatar: null,
    badge: 'Platinum',
    acceptanceRating: 91,
    experienceYears: 6,
    industries: ['Construction', 'Plumbing'],
    preferredRoles: ['Plumber', 'Maintenance Technician'],
    location: 'Perth',
    suburb: 'Subiaco',
    radiusKm: 40,
    taxTypes: ['ABN'],
    languages: ['English', 'Korean'],
    qualifications: ['Certificate III in Plumbing', 'Gas Fitter License'],
    education: 'North Metropolitan TAFE',
    availability: {
      summary: 'Mon - Sat, 8 AM - 6 PM',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    payPreference: {
      min: 45,
      max: 65,
    },
    bio: 'Licensed plumber specializing in residential and commercial installations.',
    skills: ['Pipe Installation', 'Leak Detection', 'Gas Fitting', 'Emergency Repairs'],
  },
  {
    id: 'js-011',
    name: 'Sophie Brown',
    avatar: null,
    badge: 'Bronze',
    acceptanceRating: 75,
    experienceYears: 2,
    industries: ['Retail', 'Customer Service'],
    preferredRoles: ['Sales Associate', 'Customer Service Representative'],
    location: 'Sydney',
    suburb: 'Bondi',
    radiusKm: 15,
    taxTypes: ['TFN'],
    languages: ['English'],
    qualifications: ['Certificate II in Retail'],
    education: 'TAFE NSW',
    availability: {
      summary: 'Thu - Mon, Flexible',
      days: ['Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday'],
    },
    payPreference: {
      min: 22,
      max: 30,
    },
    bio: 'Friendly sales professional with excellent customer engagement skills.',
    skills: ['Sales', 'Customer Relations', 'Cash Handling', 'Product Knowledge'],
  },
  {
    id: 'js-012',
    name: 'Ryan O\'Connor',
    avatar: null,
    badge: 'Silver',
    acceptanceRating: 85,
    experienceYears: 4,
    industries: ['Warehousing', 'Logistics'],
    preferredRoles: ['Forklift Operator', 'Warehouse Worker'],
    location: 'Melbourne',
    suburb: 'Dandenong',
    radiusKm: 30,
    taxTypes: ['TFN', 'ABN'],
    languages: ['English'],
    qualifications: ['Forklift License', 'White Card'],
    education: 'Chisholm TAFE',
    availability: {
      summary: 'Mon - Fri, Day shifts',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    },
    payPreference: {
      min: 28,
      max: 38,
    },
    bio: 'Reliable warehouse operator with strong attention to safety protocols.',
    skills: ['Forklift Operation', 'Inventory Management', 'Order Picking', 'Safety Compliance'],
  },
  {
    id: 'js-013',
    name: 'Isabella Garcia',
    avatar: null,
    badge: 'PRO',
    acceptanceRating: 94,
    experienceYears: 9,
    industries: ['Events', 'Hospitality'],
    preferredRoles: ['Event Coordinator', 'Catering Manager'],
    location: 'Sydney',
    suburb: 'Surry Hills',
    radiusKm: 35,
    taxTypes: ['ABN'],
    languages: ['English', 'Spanish', 'Italian'],
    qualifications: ['Diploma of Event Management'],
    education: 'TAFE NSW',
    availability: {
      summary: 'Mon - Sun, Flexible',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    payPreference: {
      min: 50,
      max: 75,
    },
    bio: 'Experienced event professional managing corporate and private functions.',
    skills: ['Event Planning', 'Vendor Management', 'Budget Control', 'Client Relations'],
  },
  {
    id: 'js-014',
    name: 'Mason Taylor',
    avatar: null,
    badge: 'Gold',
    acceptanceRating: 87,
    experienceYears: 5,
    industries: ['Construction', 'Electrical'],
    preferredRoles: ['Electrician', 'Electrical Apprentice'],
    location: 'Brisbane',
    suburb: 'Spring Hill',
    radiusKm: 45,
    taxTypes: ['ABN'],
    languages: ['English'],
    qualifications: ['Certificate III in Electrotechnology', 'Electrical License'],
    education: 'TAFE Queensland',
    availability: {
      summary: 'Mon - Fri, 7 AM - 5 PM',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    },
    payPreference: {
      min: 42,
      max: 58,
    },
    bio: 'Licensed electrician with expertise in residential and commercial installations.',
    skills: ['Wiring', 'Troubleshooting', 'Code Compliance', 'Safety Testing'],
  },
  {
    id: 'js-015',
    name: 'Charlotte White',
    avatar: null,
    badge: 'Platinum',
    acceptanceRating: 93,
    experienceYears: 7,
    industries: ['Cleaning Services', 'Facilities'],
    preferredRoles: ['Cleaning Supervisor', 'Commercial Cleaner'],
    location: 'Melbourne',
    suburb: 'Richmond',
    radiusKm: 30,
    taxTypes: ['ABN'],
    languages: ['English'],
    qualifications: ['Certificate III in Cleaning Operations'],
    education: 'Box Hill Institute',
    availability: {
      summary: 'Mon - Fri, Evening shifts',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    },
    payPreference: {
      min: 30,
      max: 42,
    },
    bio: 'Professional cleaner with experience in commercial and medical facilities.',
    skills: ['Deep Cleaning', 'Chemical Handling', 'Team Training', 'Quality Control'],
  },
  {
    id: 'js-016',
    name: 'Ethan Davis',
    avatar: null,
    badge: 'Bronze',
    acceptanceRating: 72,
    experienceYears: 1,
    industries: ['Hospitality', 'Food Service'],
    preferredRoles: ['Waiter', 'Barista', 'Food Runner'],
    location: 'Perth',
    suburb: 'Fremantle',
    radiusKm: 20,
    taxTypes: ['TFN'],
    languages: ['English'],
    qualifications: ['RSA Certificate', 'Barista Certificate'],
    education: 'TAFE WA',
    availability: {
      summary: 'Fri - Mon, Weekend shifts',
      days: ['Friday', 'Saturday', 'Sunday', 'Monday'],
    },
    payPreference: {
      min: 23,
      max: 30,
    },
    bio: 'Enthusiastic hospitality worker with strong customer service skills.',
    skills: ['Table Service', 'Coffee Making', 'POS Systems', 'Menu Knowledge'],
  },
  {
    id: 'js-017',
    name: 'Amelia Johnson',
    avatar: null,
    badge: 'Silver',
    acceptanceRating: 83,
    experienceYears: 3,
    industries: ['Administration', 'Data Entry'],
    preferredRoles: ['Data Entry Clerk', 'Administrative Support'],
    location: 'Adelaide',
    suburb: 'Adelaide CBD',
    radiusKm: 25,
    taxTypes: ['TFN'],
    languages: ['English'],
    qualifications: ['Certificate III in Business'],
    education: 'TAFE SA',
    availability: {
      summary: 'Mon - Fri, 9 AM - 5 PM',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    },
    payPreference: {
      min: 25,
      max: 35,
    },
    bio: 'Accurate data entry professional with attention to detail.',
    skills: ['Data Entry', 'Microsoft Excel', 'Filing', 'Phone Etiquette'],
  },
  {
    id: 'js-018',
    name: 'Lucas Rodriguez',
    avatar: null,
    badge: 'Gold',
    acceptanceRating: 88,
    experienceYears: 6,
    industries: ['Construction', 'Tiling'],
    preferredRoles: ['Tiler', 'Flooring Specialist'],
    location: 'Sydney',
    suburb: 'Bankstown',
    radiusKm: 40,
    taxTypes: ['ABN'],
    languages: ['English', 'Spanish'],
    qualifications: ['Certificate III in Wall and Floor Tiling'],
    education: 'TAFE NSW',
    availability: {
      summary: 'Mon - Sat, 8 AM - 5 PM',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    payPreference: {
      min: 35,
      max: 50,
    },
    bio: 'Skilled tiler specializing in ceramic, porcelain, and natural stone installations.',
    skills: ['Tile Installation', 'Grouting', 'Pattern Layout', 'Waterproofing'],
  },
  {
    id: 'js-019',
    name: 'Zoe Mitchell',
    avatar: null,
    badge: 'PRO',
    acceptanceRating: 97,
    experienceYears: 10,
    industries: ['Hospitality', 'Management'],
    preferredRoles: ['Restaurant Manager', 'Operations Manager'],
    location: 'Melbourne',
    suburb: 'St Kilda',
    radiusKm: 35,
    taxTypes: ['ABN'],
    languages: ['English', 'French'],
    qualifications: ['Diploma of Hospitality Management'],
    education: 'William Angliss Institute',
    availability: {
      summary: 'Mon - Sun, Flexible',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    payPreference: {
      min: 55,
      max: 80,
    },
    bio: 'Experienced hospitality manager with proven track record in operations and team leadership.',
    skills: ['Staff Management', 'Inventory Control', 'Customer Relations', 'Financial Management'],
  },
  {
    id: 'js-020',
    name: 'Jack Thompson',
    avatar: null,
    badge: 'Platinum',
    acceptanceRating: 90,
    experienceYears: 5,
    industries: ['Construction', 'Concreting'],
    preferredRoles: ['Concretor', 'Formworker'],
    location: 'Brisbane',
    suburb: 'Logan',
    radiusKm: 50,
    taxTypes: ['ABN'],
    languages: ['English'],
    qualifications: ['Certificate III in Concreting'],
    education: 'TAFE Queensland',
    availability: {
      summary: 'Mon - Fri, 6 AM - 4 PM',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    },
    payPreference: {
      min: 38,
      max: 52,
    },
    bio: 'Experienced concretor with expertise in driveways, slabs, and decorative finishes.',
    skills: ['Concrete Pouring', 'Formwork', 'Finishing', 'Curing'],
  },
];

export const getRandomBadge = () => {
  const index = Math.floor(Math.random() * badgeLevels.length);
  return badgeLevels[index];
};

