const badgeLevels = ['Bronze', 'Silver', 'Gold', 'Platinum'];

export const DUMMY_JOB_SEEKERS = [
  {
    id: 'js-001',
    name: 'Jane Jobseeker',
    avatar: null,
    badge: 'Gold',
    acceptanceRating: 92,
    experienceYears: 4,
    industries: ['Construction', 'Maintenance'],
    preferredRoles: ['Painter', 'Decorator'],
    location: 'Sydney',
    suburb: 'Parramatta',
    radiusKm: 25,
    taxTypes: ['ABN'],
    languages: ['English'],
    qualifications: ['Certificate III in Painting and Decorating'],
    education: 'TAFE NSW',
    availability: {
      summary: 'Mon - Fri, 8 AM - 5 PM',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    },
    payPreference: {
      min: 28,
      max: 38,
    },
    bio: 'Detail-oriented painter with experience across residential and commercial projects.',
    skills: ['Painting', 'Surface Prep', 'Team Leadership'],
  },
  {
    id: 'js-002',
    name: 'Michael Torres',
    avatar: null,
    badge: 'Platinum',
    acceptanceRating: 88,
    experienceYears: 6,
    industries: ['Logistics', 'Warehousing'],
    preferredRoles: ['Warehouse Manager', 'Inventory Lead'],
    location: 'Melbourne',
    suburb: 'Footscray',
    radiusKm: 30,
    taxTypes: ['TFN', 'ABN'],
    languages: ['English', 'Spanish'],
    qualifications: ['Diploma in Logistics Management'],
    education: 'Victoria University',
    availability: {
      summary: 'Mon - Sat, Day shifts',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    payPreference: {
      min: 32,
      max: 45,
    },
    bio: 'Warehouse professional focused on process optimisation and safety.',
    skills: ['Inventory Systems', 'Team Training', 'Forklift Operation'],
  },
  {
    id: 'js-003',
    name: 'Aisha Khan',
    avatar: null,
    badge: 'Bronze',
    acceptanceRating: 78,
    experienceYears: 2,
    industries: ['Events', 'Hospitality'],
    preferredRoles: ['Event Crew', 'Logistics Assistant'],
    location: 'Brisbane',
    suburb: 'Fortitude Valley',
    radiusKm: 20,
    taxTypes: ['ABN'],
    languages: ['English', 'Hindi'],
    qualifications: ['Certificate II in Hospitality'],
    education: 'TAFE Queensland',
    availability: {
      summary: 'Thu - Sun, Afternoon & Night',
      days: ['Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    payPreference: {
      min: 22,
      max: 32,
    },
    bio: 'Reliable event crew member experienced with rapid setup and packdown.',
    skills: ['Customer Service', 'Manual Handling', 'Scheduling'],
  },
  {
    id: 'js-004',
    name: 'Liam Chen',
    avatar: null,
    badge: 'Silver',
    acceptanceRating: 84,
    experienceYears: 5,
    industries: ['Cleaning Services', 'Facilities'],
    preferredRoles: ['Cleaning Supervisor', 'Deep Cleaning Specialist'],
    location: 'Perth',
    suburb: 'Scarborough',
    radiusKm: 35,
    taxTypes: ['TFN'],
    languages: ['English', 'Mandarin'],
    qualifications: ['Workplace Health & Safety (Level 2)'],
    education: 'North Metropolitan TAFE',
    availability: {
      summary: 'Mon - Fri, Evening & Night',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    },
    payPreference: {
      min: 26,
      max: 36,
    },
    bio: 'Cleaning supervisor experienced with large commercial kitchens and hospitality venues.',
    skills: ['Team Leadership', 'Chemical Handling', 'Quality Assurance'],
  },
  {
    id: 'js-005',
    name: 'Sofia Romero',
    avatar: null,
    badge: 'Gold',
    acceptanceRating: 95,
    experienceYears: 7,
    industries: ['Landscaping', 'Outdoor Projects'],
    preferredRoles: ['Landscape Designer', 'Project Lead'],
    location: 'Adelaide',
    suburb: 'Norwood',
    radiusKm: 40,
    taxTypes: ['ABN'],
    languages: ['English', 'Spanish'],
    qualifications: ['Bachelor of Landscape Architecture'],
    education: 'University of Adelaide',
    availability: {
      summary: 'Mon - Sat, Flexible',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    payPreference: {
      min: 35,
      max: 55,
    },
    bio: 'Landscape professional specialising in bespoke outdoor experiences.',
    skills: ['Design', 'Site Management', 'Client Liaison'],
  },
  {
    id: 'js-006',
    name: 'Noah Wilson',
    avatar: null,
    badge: 'Bronze',
    acceptanceRating: 70,
    experienceYears: 1,
    industries: ['Retail', 'Customer Service'],
    preferredRoles: ['Store Assistant', 'Visual Merchandiser'],
    location: 'Gold Coast',
    suburb: 'Southport',
    radiusKm: 15,
    taxTypes: ['TFN'],
    languages: ['English'],
    qualifications: ['Certificate III in Retail'],
    education: 'TAFE Queensland',
    availability: {
      summary: 'Wed - Sun, Morning shifts',
      days: ['Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    payPreference: {
      min: 20,
      max: 28,
    },
    bio: 'Retail professional with an eye for detail and merchandising layouts.',
    skills: ['POS Systems', 'Visual Merchandising', 'Stock Control'],
  },
];

export const getRandomBadge = () => {
  const index = Math.floor(Math.random() * badgeLevels.length);
  return badgeLevels[index];
};

