export const screenNames = {
  SPLASH: 'splash',
  ROOT_STACK: 'root_stack',
  ROOT_NAVIGATION: 'root_navigation',
  AUTH_NAVIGATION: 'auth_navigation',
  MAIN_NAVIGATION: 'main_navigation',
  DRAWER_NAVIGATION: 'drawer_navigator',
  SIGN_IN: 'sign_in',
  ON_BOARDING: 'on_boarding',
  SIGN_UP: 'sign_up',
  VERIFY_EMAIL: 'verify_email',
  HOME: 'home',
  CHAT: 'chat',
  FIND_STAFF: 'find_staff',
  Wallet: 'wallet',
  // SIGN_IN: 'sign_in',
  // HOME: 'Home',
  Tab_NAVIGATION: 'tab_navigation',
  ACTIVE_JOB_OFFERS: 'active_job_offers',
  JOB_PREVIEW: 'job_preview',
  QUICK_SEARCH: 'quick_search',
  MANUAL_SEARCH: 'manual_search',
  
  ACCOUNT_DETAILS: 'account_details',
  PURCHASE_COINS: 'purchase_coins',
  WITHDRAW_COINS: 'withdraw_coins',
  BANK_DETAILS: 'bank_details',
  FORM_SUMMARY: 'form_summary',

  WALLET_STACK: 'wallet_stack', 

  MESSAGES: 'messages',

  ABILITY_TO_WORK: 'ability_to_work',
  STEP_TWO: 'step_two',
  STEP_THREE: 'step_three',

  // FORGOT_PASSWORD: 'forgot_password',
  // CHECK_EMAIL: 'check_email',
  // CREATE_PASSWORD: 'create_password',
  // PASSWORD_RESET: 'password_reset',
  // HOME_SCREEN: 'home_screen',
  // ADD_LOCATION: 'add_location',
  // ATTENDANCE_SCREEN: 'attendance_screen',
  // PROJECT_SCREEN: 'project_screen',
  // PAYROLL_SCREEN: 'payroll_screen',
  // SCHEDUL_SCREEN: 'schedul_screen',
  // MY_PROFILE: 'my_profile',
  // EDIT_PROFILE: 'edit_profile',
  // CHANGE_PASSWORD: 'change_password',
  // NOTIFICATION_SETTINGS: 'notification_settings',
  // PROJECT_DETAILS: 'project_details',
  // WEEK_SCHEDULE_SCREEN: "Week_schedule_screen",
  // SINGLE_USER_SCHEDULE: "Single_user_schedule",
  // ADD_SCHEDULE: "add_schedule",
  // ALL_DEPARTMENTS: "all_departments",
  // ALL_EMPLOYEES: "all_employees",
  // ADD_NEW_EMPLOYEE: "add_new_employee",
  // CANDIDATES_SCREEN: "candidates_screen",
  // JOBS_SCREEN: "jobs_screen",
  // JOB_DETAILS: "job_details",
  // CREATE_JOB: "create_job",
  // EMPLOYEE_DETAILS: "employee_details",
  // ADD_CANDIDATE: "add_candidate",
  // PRIVACY_POLICY: 'privacy_policy',
  // MY_AVAILABILITY: 'my_availability',
  // CHAT_SCREEN: 'chat_screen',
  // CHAT_DETAIL: 'chat_detail',
  // REQUEST_SCREEN: 'request_screen',
  // NOTIFICATION_SCREEN:'notifiction_screen',
  // LANGUAGE_SCREEN: 'language_screen',
};
