export const screenNames = {
  SPLASH: 'splash',
  ROOT_STACK: 'root_stack',
  ROOT_NAVIGATION: 'root_navigation',
  AUTH_NAVIGATION: 'auth_navigation',
  MAIN_NAVIGATION: 'main_navigation',
  DRAWER_NAVIGATION: 'drawer_navigator',
  JOBSEEKER_DRAWER: 'jobseeker_drawer',
  SIGN_IN: 'sign_in',
  ON_BOARDING: 'on_boarding',
  SIGN_UP: 'sign_up',
  VERIFY_EMAIL: 'verify_email',
  HOME: 'home',
  CHAT: 'chat',
  FIND_STAFF: 'find_staff',
  Wallet: 'wallet',
  // SIGN_IN: 'sign_in',
  // HOME: 'Home',
  Tab_NAVIGATION: 'tab_navigation',
  JOBSEEKER_TAB: 'jobseeker_tab',
  ACTIVE_JOB_OFFERS: 'active_job_offers',
  JOB_PREVIEW: 'job_preview',
  VIEW_JOB_DETAILS: 'view_job_details',
  JOB_CANDIDATES: 'job_candidates',
  QUICK_SEARCH: 'quick_search',
  MANUAL_SEARCH: 'manual_search',
  MANUAL_SEARCH_STACK: 'manual_search_stack',
  MANUAL_MATCH_LIST: 'manual_match_list',
  MANUAL_CANDIDATE_PROFILE: 'manual_candidate_profile',
  MANUAL_OFFERS: 'manual_offers',
  
  ACCOUNT_DETAILS: 'account_details',
  PURCHASE_COINS: 'purchase_coins',
  WITHDRAW_COINS: 'withdraw_coins',
  BANK_DETAILS: 'bank_details',
  FORM_SUMMARY: 'form_summary',

  WALLET_STACK: 'wallet_stack', 

  MESSAGES: 'messages',

  ABILITY_TO_WORK: 'ability_to_work',
  STEP_TWO: 'step_two',
  STEP_THREE: 'step_three',
  MAIN_DASHBOARD: 'main_dashboard',
  LABOR_POOL: 'labor_pool',
  SQUAD_POOL: 'squad_pool',
  CONTRACTORS: 'contractors',
  ACTIVE_OFFERS: 'active_offers',
  DRAFTED_OFFERS: 'drafted_offers',
  COMPLETED_OFFERS: 'completed_offers',
  EXPIRED_OFFERS: 'expired_offers',
  STAFF_PREFERENCES: 'staff_preferences',
  UPDATE_MAIN: 'update_main',
  UPDATE_SECOND: 'update_second',
  UPDATE_THIRD: 'update_third',
  NOTICATIONS: 'notifications',
  QUICK_SEARCH_STEPONE:'quick_search_stepone',
QUICK_SEARCH_STEPTWO:'manual_search_steptwo',
QUICK_SEARCH_STEPTHREE:'manual_search_stepthree',
QUICK_SEARCH_STEPFOUR:'manual_search_stepfour',
  JOBSEEKER_SETTINGS:'jobseeker_settings',

   JOB_SETTINGS: 'job_settings',
  APP_SETTINGS: 'app_settings',
  SQUAD_SETTINGS: 'squad_settings',

  ACCOUNT_UPGRADE: 'account_upgrade',
  SUPPORT: 'support',
  SUPPORT_FAQ: 'support_faq',
  SUPPORT_TICKETS: 'support_tickets',

  PROFILE: 'profile',
  BASIC_DETAILS: 'BasicDetails',
  ADDRESS: 'Address',
  CONTACT_DETAILS: 'ContactDetails',
  TAX_INFO: 'TaxInfo',
  VISA_DETAILS: 'VisaDetails',
  KYC_KYB: 'KycKyb',
  EXTRA_QUALIFICATIONS: 'ExtraQualifications',
  BIO: 'BioScreen',
  SOCIAL_MEDIA: 'SocialMedia',
  PASSWORD: 'PasswordScreen',
  KYC_KYB_DOC:'kyc_kyb_doc',
  KYC_KYB_SUBMIT:'kyc_kyb_submit',
  JOB_SEEKER_DASHBOARD:'job_seeker_dashboard',
  WORK_EXPERIENCE:'work_experience',
  MARKET_PLACE:'market_place',
MARKETPLACE_STACK:'marketplace_stack',
PRODUCT_DETAILS:'product_details',
POST_PRODUCT:'post_product',
MARKETPLACE_CART:'marketplace_cart',
MARKETPLACE_FAVORITES:'marketplace_favorites',
MARKETPLACE_CHECKOUT:'marketplace_checkout',
MARKETPLACE_PAYMENT:'marketplace_payment',
MARKETPLACE_ORDERS:'marketplace_orders',
MARKETPLACE_ORDER_DETAILS:'marketplace_order_details',
KYC_BUSINESS:'kyc_business',
ADD_EXPERIENCE:'add_experience',
ADD_JOB_STEP1:'add_job_step1',
ADD_JOB_STEP2:'add_job_step2',
SQUAD_SETTINGS_Groups:'squad_settings_groups',
GROUP_DETAIL:'group_detail',
MEMBERS:'members',
EDIT_PROFILE:'edit_profile',
QUICK_SEARCH_PREVIEW:'quick_search_preview',

JOB_OFFER_DETAILS: 'job_offer_details',
ACCEPTED_OFFERS: 'accepted_offers',


  // FORGOT_PASSWORD: 'forgot_password',
  // CHECK_EMAIL: 'check_email',
  // CREATE_PASSWORD: 'create_password',
  // PASSWORD_RESET: 'password_reset',
  // HOME_SCREEN: 'home_screen',
  // ADD_LOCATION: 'add_location',
  // ATTENDANCE_SCREEN: 'attendance_screen',
  // PROJECT_SCREEN: 'project_screen',
  // PAYROLL_SCREEN: 'payroll_screen',
  // SCHEDUL_SCREEN: 'schedul_screen',
  // MY_PROFILE: 'my_profile',
  // EDIT_PROFILE: 'edit_profile',
  // CHANGE_PASSWORD: 'change_password',
  // NOTIFICATION_SETTINGS: 'notification_settings',
  // PROJECT_DETAILS: 'project_details',
  // WEEK_SCHEDULE_SCREEN: "Week_schedule_screen",
  // SINGLE_USER_SCHEDULE: "Single_user_schedule",
  // ADD_SCHEDULE: "add_schedule",
  // ALL_DEPARTMENTS: "all_departments",
  // ALL_EMPLOYEES: "all_employees",
  // ADD_NEW_EMPLOYEE: "add_new_employee",
  // CANDIDATES_SCREEN: "candidates_screen",
  // JOBS_SCREEN: "jobs_screen",
  // JOB_DETAILS: "job_details",
  // CREATE_JOB: "create_job",
  // EMPLOYEE_DETAILS: "employee_details",
  // ADD_CANDIDATE: "add_candidate",
  // PRIVACY_POLICY: 'privacy_policy',
  // MY_AVAILABILITY: 'my_availability',
  // CHAT_SCREEN: 'chat_screen',
  // CHAT_DETAIL: 'chat_detail',
  // REQUEST_SCREEN: 'request_screen',
  // NOTIFICATION_SCREEN:'notifiction_screen',
  // LANGUAGE_SCREEN: 'language_screen',
};
